version: 2
jobs:
  build-n-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: make build version=${CIRCLE_TAG}
      - run:
          name: Run
          command: make run version=${CIRCLE_TAG}
      - run:
          name: Test
          command: make test

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-n-deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
