version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Test
          command: make build

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
#      - deploy:
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
