version: 2
jobs:
  build-n-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Run
          command: make run
      - run:
          name: test
          command: curl -v localhost

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-n-deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
